#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ -d '/usr/local/emps' ]; then
    if [ -z "$(ls -A /usr/local/emps)" ]; then
        echo root:"$PASSWORD" | chpasswd
        adduser --disabled-login --gecos "" emps > /dev/null 2>&1
        bash /etc/scripts/install-virtualizor.sh
        echo ""
        echo "Press CTRL+C to exit the installation."
        echo "You can start the panel in the background with: sh virtualizor.sh start"
        echo ""
    else
        if ! id -u mysql &>/dev/null; then
            adduser --disabled-login --gecos "" mysql > /dev/null 2>&1
        fi
        if ! id -u emps &>/dev/null; then
            adduser --disabled-login --gecos "" emps > /dev/null 2>&1
        fi
        /etc/init.d/virtualizor start 2>&1
    fi
fi