#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo root:"$PASSWORD" | chpasswd

if [ -d '/usr/local/emps' ]; then
    if [ -z "$(ls -A /usr/local/emps)" ] || [ -z "$(ls -A /usr/local/virtualizor)" ]; then
        adduser --disabled-login --gecos "" emps > /dev/null 2>&1
        bash /etc/scripts/install-virtualizor.sh
        echo ""
        echo "Press CTRL+C to exit the installation."
        echo "You can start the panel in the background with:"
        echo " - docker start virtualizor" # To-Do : make this container aware
        echo ""
    else
        if ! id -u mysql &>/dev/null; then
            adduser --disabled-login --gecos "" mysql > /dev/null 2>&1
        fi
        if ! id -u emps &>/dev/null; then
            adduser --disabled-login --gecos "" emps > /dev/null 2>&1
        fi
        /etc/init.d/virtualizor start 2>&1
    fi
fi