name: Publish latest docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Additional Docker image tag'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          sbom: true # https://docs.docker.com/build/ci/github-actions/attestations/
          provenance: mode=max
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/virtualizor-docker:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/virtualizor-docker:${{ github.event.inputs.tag}}